language: go
go:
- 1.7
- tip
before_install:
  # install etcd
  - wget https://github.com/coreos/etcd/releases/download/v3.0.6/etcd-v3.0.6-linux-amd64.tar.gz
  - tar xzf etcd-v3.0.6-linux-amd64.tar.gz
  - sudo mv etcd-v3.0.6-linux-amd64/etcd /bin/
  - etcd &
install:
- ./build
- sudo ./install
script:
  - ./test
